file = open('file1.txt', 'r')
print(file.read())
file.close()
file = open("file1.txt", 'r')
print(file.read(5))
file.close()
file = open("file1.txt", 'a')
file.write("This is a new line.")
file.close()
file = open("file1.txt", 'r')
print(file.read())